#项目版本
application:
  version: 1.0.0
  formattedVersion: (v1.0.0)

server:
  port: 8082

#spring设置
spring:
  profiles:
    active: MSSql
  application:
    name: admin
  servlet:
    multipart:
      maxFileSize: 1000MB
      maxRequestSize: 1000MB
      enabled: true
  cloud:
      inetutils:
        ignored-interfaces:
          - dockre0
  datasource:
    master:
      jdbc-url: jdbc:sqlserver://36.133.97.90;DatabaseName=cloudhis
      username: sa
      password: ENC(afL/r/PkdUUZp8Jz0X7WBkGJNVdFr1V6)
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    slave:
      jdbc-url: jdbc:sqlserver://36.133.97.90;DatabaseName=cloudhis
      username: sa
      password: ENC(afL/r/PkdUUZp8Jz0X7WBkGJNVdFr1V6)
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
  data:
    mongodb:
      database: cloudhis
      host: 36.133.97.90
      port: 27017
      username: cz
      password: ENC(R2k4yeYBfqoYR6PV2nsuCA==)
  redis:
    database: 0
    host: 36.133.97.90
    password: ENC(R2k4yeYBfqoYR6PV2nsuCA==)
    port: 6379
    timeout: 1000
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    async:
      request-timeout: 60000000
  jackson:
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    multipart:
      location: /data/upload_tmp

config:
  jwt:
    # 加密密钥 密钥属性不能太短 太短报错
    secret: ENC(AJi7fNYGP1l/vH8HXv9pRzRXWnFQr6ac)
    # token有效时长 秒
    expire: 36000
    # header 名称
    header: Authorization

eureka:
  instance:
    # 续约更新时间间隔（默认30秒）
    leaseEexpirationDurationInSeconds: 30
    # 续约到期时间（默认90秒）
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
  servername: wcz.yiruan01.com
  serverport: 8081
  client:
    healthcheck:
      # 开启健康检查（需要spring-boot-starter-actuator依赖）
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.servername}:${eureka.serverport}/eureka/

fdfs:
  soTimeout: 1500000 #socket连接超时时长
  connectTimeout: 600000 #连接tracker服务器超时时长
  resHost: 47.108.203.35
  storagePort: 8888
  trackerList: 
    - 47.108.203.35:22122

############  actuator监控  ############
management:
  health:
    diskSpace:
      enabled: true
    db:
      enabled: true
    redis:
      enabled: true
    mongo:
      enabled: true
    elasticsearch:
      enabled: false
    mail:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
